/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package workshop_graphics;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import javax.swing.JColorChooser;

/**
 *
 * @author nguye
 */
public class Slot16 extends javax.swing.JFrame {

    Color color = Color.RED;
    Point p1 = null, p2 = null;
    Graphics g;

    /**
     * Creates new form Slot16
     */
    public Slot16() {
        initComponents();
        rbtnDraw.setSelected(true);
        g = linePanel.getGraphics();
        rbtnDFill.setEnabled(false);
        rbtnDraw.setSelected(true);
        g.setColor(color);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tablledPanel = new javax.swing.JTabbedPane();
        linePanel = new javax.swing.JPanel();
        rectanglePanel = new javax.swing.JPanel();
        ovalPanel = new javax.swing.JPanel();
        jlColor = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        rbtnDraw = new javax.swing.JRadioButton();
        rbtnDFill = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablledPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablledPanelMouseClicked(evt);
            }
        });

        linePanel.setPreferredSize(new java.awt.Dimension(725, 400));
        linePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                linePanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                linePanelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout linePanelLayout = new javax.swing.GroupLayout(linePanel);
        linePanel.setLayout(linePanelLayout);
        linePanelLayout.setHorizontalGroup(
            linePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );
        linePanelLayout.setVerticalGroup(
            linePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );

        tablledPanel.addTab("Lines", linePanel);

        rectanglePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rectanglePanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rectanglePanelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout rectanglePanelLayout = new javax.swing.GroupLayout(rectanglePanel);
        rectanglePanel.setLayout(rectanglePanelLayout);
        rectanglePanelLayout.setHorizontalGroup(
            rectanglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );
        rectanglePanelLayout.setVerticalGroup(
            rectanglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );

        tablledPanel.addTab("Rectangle", rectanglePanel);

        ovalPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ovalPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ovalPanelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout ovalPanelLayout = new javax.swing.GroupLayout(ovalPanel);
        ovalPanel.setLayout(ovalPanelLayout);
        ovalPanelLayout.setHorizontalGroup(
            ovalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );
        ovalPanelLayout.setVerticalGroup(
            ovalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );

        tablledPanel.addTab("Oval", ovalPanel);

        jlColor.setBackground(new java.awt.Color(255, 0, 0));
        jlColor.setOpaque(true);

        jButton1.setText("Set Color");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnDraw);
        rbtnDraw.setText("Draw");

        buttonGroup1.add(rbtnDFill);
        rbtnDFill.setText("Fill and Draw");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlColor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(rbtnDraw)
                .addGap(39, 39, 39)
                .addComponent(rbtnDFill)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(tablledPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbtnDraw)
                        .addComponent(rbtnDFill)))
                .addGap(20, 20, 20)
                .addComponent(tablledPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jlColor});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        color = JColorChooser.showDialog(rootPane, "Please pick a color", color);
        jlColor.setBackground(color);
        g.setColor(color);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablledPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablledPanelMouseClicked
        int index = tablledPanel.getSelectedIndex();
        switch (index) {
            case 0:
                g = linePanel.getGraphics();
                rbtnDFill.setEnabled(false);
                rbtnDraw.setSelected(true);
                break;
            case 1:
                g = rectanglePanel.getGraphics();
                rbtnDFill.setEnabled(true);
                break;
            case 2:
                g = ovalPanel.getGraphics();
                rbtnDFill.setEnabled(true);
                break;
        }
        g.setColor(color);
    }//GEN-LAST:event_tablledPanelMouseClicked

    private void linePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linePanelMousePressed
        p1 = evt.getPoint();
    }//GEN-LAST:event_linePanelMousePressed

    private void linePanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linePanelMouseReleased
        p2 = evt.getPoint();
        g.drawLine(p1.x, p1.y, p2.x, p2.y);
        p1 = p2 = null;
    }//GEN-LAST:event_linePanelMouseReleased

    private void rectanglePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rectanglePanelMousePressed
        p1 = evt.getPoint();
    }//GEN-LAST:event_rectanglePanelMousePressed

    private void rectanglePanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rectanglePanelMouseReleased
        p2 = evt.getPoint();

        int left = Math.min(p1.x, p2.x);
        int top = Math.min(p1.y, p2.y);
        int width = Math.abs(p1.x - p2.x);
        int height = Math.abs(p1.y - p2.y);
        if (rbtnDraw.isSelected()) {
            g.drawRect(left, top, width, height);
        } else {
            g.fillRect(left, top, width, height);
        }
        p1 = p2 = null;
    }//GEN-LAST:event_rectanglePanelMouseReleased

    private void ovalPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ovalPanelMousePressed
        p1 = evt.getPoint();
    }//GEN-LAST:event_ovalPanelMousePressed

    private void ovalPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ovalPanelMouseReleased
        p2 = evt.getPoint();

        int left = Math.min(p1.x, p2.x);
        int top = Math.min(p1.y, p2.y);
        int width = Math.abs(p1.x - p2.x);
        int height = Math.abs(p1.y - p2.y);
        if (rbtnDraw.isSelected()) {
            g.drawOval(left, top, width, height);
        } else {
            g.fillOval(left, top, width, height);
        }
        p1 = p2 = null;
    }//GEN-LAST:event_ovalPanelMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Slot16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Slot16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Slot16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Slot16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Slot16().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jlColor;
    private javax.swing.JPanel linePanel;
    private javax.swing.JPanel ovalPanel;
    private javax.swing.JRadioButton rbtnDFill;
    private javax.swing.JRadioButton rbtnDraw;
    private javax.swing.JPanel rectanglePanel;
    private javax.swing.JTabbedPane tablledPanel;
    // End of variables declaration//GEN-END:variables
}
